engines:
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_paths:
  - grifts/**/*
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - logs/*
  - public/*
  - templates/*
  - assets/vendor/**
ratings:
  paths:
    - "**.go"
