language: go
dist: bionic

go:
  - 1.16.x

# sudo enabled, fully virtualized virtual machine required for mysql 5.7.
# https://docs.travis-ci.com/user/database-setup/#mysql
# https://docs.travis-ci.com/user/reference/trusty/

services:
  - mysql

env:
  global:
    - GO_ENV=test
    - CC_TEST_REPORTER_ID=871aa7166cc89677d1839bca6a9213454dcc94344f8ef937f07360e255cb774c

before_install:
  - nvm --version
  - nvm install 14.17.4
  - node --version
  - env
  - mysql --version
  - wget -O - https://github.com/gobuffalo/cli/releases/download/v0.18.0/buffalo_0.18.0_Linux_x86_64.tar.gz |tar zxv
  - mv buffalo $GOPATH/bin/buffalo
  - go get -v github.com/gobuffalo/buffalo-pop/v3
  - ls -l $GOPATH/bin
  - buffalo version
  - buffalo help
  - buffalo-pop help
  - go install github.com/mattn/goveralls@latest

install:
  - go mod tidy
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - yarn
  - sh ./scripts/keygen.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

go_import_path: github.com/hyeoncheon/uart

script:
  - >
    go mod tidy &&
    cat go.mod go.sum
  - >
    buffalo build --skip-assets &&
    ls -l bin/uart &&
    cp database.yml.travis database.yml &&
    UART_HOME=`pwd` buffalo test -coverprofile=c.out -covermode=count ./... &&
    ./cc-test-reporter after-build --exit-code 0 &&
    buffalo pop drop -e test &&
    buffalo pop create -e test &&
    buffalo pop migrate -e test &&
    UART_HOME=`pwd` goveralls -v -service=travis-ci

after_script: true

after_success:
  # for codecov.io
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -v -f c.out
