language: go

go:
  - 1.8.x

env:
  - GO_ENV=test

before_script:
  - mysql -e 'CREATE DATABASE uart_test;'
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - npm install --no-progress

go_import_path: github.com/hyeoncheon/uart

script:
  - buffalo build --static

