language: go

go:
  - "1.9"
  - "1.10"
  - "1.11.1"

# sudo enabled, fully virtualized virtual machine required for mysql 5.7.
# https://docs.travis-ci.com/user/database-setup/#MySQL-5.7
# https://docs.travis-ci.com/user/reference/trusty/

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    package:
      - mysql-server
      - mysql-client

env:
  global:
    - GO_ENV=test
    - CC_TEST_REPORTER_ID=871aa7166cc89677d1839bca6a9213454dcc94344f8ef937f07360e255cb774c

before_install:
  - sudo mysql_upgrade --force
  - sudo service mysql restart
  - mysql --version
  - go get -u github.com/golang/dep/cmd/dep
  - wget -O - https://github.com/gobuffalo/buffalo/releases/download/v0.13.4/buffalo_0.13.4_linux_amd64.tar.gz |tar zxv
  - mv buffalo-no-sqlite $GOPATH/bin/buffalo
  - wget -O - https://github.com/gobuffalo/buffalo-pop/releases/download/v1.1.12/buffalo-pop_1.1.12_linux_amd64.tar.gz |tar zxv
  - mv buffalo-pop $GOPATH/bin/
  - ls -l $GOPATH/bin
  - ls -ld $GOPATH/src/*/*
  - buffalo help

install:
  - dep ensure
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - npm install --no-progress
  - sh ./scripts/keygen.sh

before_script:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/AlekSi/gocoverutil
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - buffalo build
  #
  - cp database.yml.travis database.yml
  - buffalo pop create -e test
  - buffalo pop migrate -e test
  - UART_HOME=`pwd` GO_ENV=test gocoverutil -coverprofile=c.out -ignore=./vendor/... test -covermode=count ./... && ./cc-test-reporter after-build --exit-code 0
  #
  - buffalo pop drop -e test
  - buffalo pop create -e test
  - buffalo pop migrate -e test
  - UART_HOME=`pwd` goveralls -service=travis-ci

after_script: true

after_success:
  # for codecov.io
  - cp c.out coverage.txt
  - bash <(curl -s https://codecov.io/bash)

