language: go

go:
  - 1.8.x

env:
  - GO_ENV=test

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get github.com/mattn/goveralls
  - npm install --no-progress
  - cp database.yml.travis database.yml
  # `mysql ...` instead of `buffalo db create`. work-around for empty password.
  - mysql -e 'CREATE DATABASE hc_uart_test;'
  - buffalo db migrate -e test
  - sh ./scripts/keygen.sh

go_import_path: github.com/hyeoncheon/uart

script:
  - buffalo build --static
  - UART_HOME=`pwd` goveralls -service=travis-ci
