language: go

go:
  - 1.8.x

env:
  - GO_ENV=test

before_script:
  - mysql -e 'CREATE DATABASE uart_test;'
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/hyeoncheon/uart

script:
  - go build
