development:
  dialect: "mysql"
  database: "uart_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@localhost:3306/uart_test"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@localhost:3306/uart_production"}}